@baseUrl = http://localhost:3000
@route = api/pets

### Create Pet
POST {{baseUrl}}/{{route}}/
Content-Type: application/json

{
  "name": "FidoBorrar",
  "species": "dog",
  "ownerId": "68924cda96348cf328284478"
}


### Get all pets
GET {{baseUrl}}/{{route}}/
Accept: application/json

### Delete Pet
DELETE {{baseUrl}}/{{route}}/689311c3d1d787911f79c512