@baseUrl = http://localhost:3000
@route = api/users

### Create User
POST {{baseUrl}}/{{route}}/
Content-Type: application/json

{
  "name": "userborrar",
  "email": "user@gmail.com"
}

### Get all users
GET {{baseUrl}}/{{route}}/
Accept: application/json

### Get User By Id
GET {{baseUrl}}/{{route}}/68924cda96348cf328284478

### Update User
PATCH  {{baseUrl}}/{{route}}/6872d69daca8b7a666f0c486
Content-Type: application/json

{
  "role": "ADMIN"
}

### Delete User
DELETE {{baseUrl}}/{{route}}/6893120ad1d787911f79c516